Sly data converter
ViacheslavDanilov/oct_segmentation pull request #6
Opened 2023-02-15 09:32 UTC by Vladislav26Laptev

2023-02-15 09:42 UTC, ViacheslavDanilov requested changes
@Vladislav26Laptev 

1. **Image path**. Лучше указывать путь до изображения, а не до его директории т.е. вот так **data/interim/img/my_image.png**
2. **Image name**. Предлагаю изменить формат на XXX_Y_ZZZ.png, где XXX - study, Y - series, ZZZ - slice т.е. *005_1_235.png*
3. **Series** колонки нет.
4. **Slice** колонка пустая.
5. Может не удалять нижнюю часть изображения? Я думаю, что лучше это сделать на этапе конвертации в нужный для сети формат.

2023-02-15 13:09 UTC, Vladislav26Laptev commented
Series колонки нет потому что ее нет в данных supervisely (нужен пример как это будет выглядеть)
Папка с двумя и более видео?

2023-02-15 13:32 UTC, ViacheslavDanilov commented on config/data_sly.yaml
>  meta:
Почему называется meta? У нас уже есть такой конфиг, тем более он совсем к другим вещам относится.

2023-02-15 13:33 UTC, ViacheslavDanilov commented on config/data_sly.yaml
> +  window_position: [[0, 0], [1000, 1000]]
Нужно перенести этот конфиг в **data.yaml**, а старый data_sly.yaml удалить

2023-02-15 13:36 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +    images_dir = os.path.join(cfg.meta.save_dir, 'img')
Нужно разбить main на подфункции т.к. слишком большая и тяжёлая для понимания и чтения.

В main должны последовательно вызываться вспомогательные функции.

2023-02-16 17:19 UTC, ViacheslavDanilov commented on config/data.yaml
> +  study_dir: data/sly_output
В [**main**](https://github.com/ViacheslavDanilov/oct_segmentation/tree/main/data) уже лежит основная структура датасета, поэтому не нужно придумывать новую.

Изменил, чтобы соответствовало **main**'у

2023-02-16 17:19 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +id = 0
Пока не понятно зачем он нужен

2023-02-16 17:23 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +):
Конфиг **cfg** передаётся в main, а остальные функции/методы должны использовать свои собственные аргументы т.е. если ты сейчас используешь **cfg.sly_to_int.save_dir**, то его нужно изменить на save_dir и передавать его значение

2023-02-16 17:26 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +                'Class': classTitle,
Нэйминг точно не по PEP8. Camel Case нотация это у Java или MATLAB, у **Python** - **Snake Case**.

2023-02-16 17:27 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +):
Конфиг **cfg** передаётся в main, а остальные функции/методы должны использовать свои собственные аргументы т.е. если ты сейчас используешь **cfg.sly_to_int.save_dir**, то его нужно изменить на **save_dir** и передавать его значение

2023-02-16 17:29 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +        classTitle = obj.classTitle.values[0]
Нэйминг точно не по PEP8. Camel Case нотация это у Java или MATLAB, у Python - Snake Case.

2023-02-16 17:35 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +            ] = mask_[:, :]
To discuss

2023-02-16 17:40 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +):
Конфиг **cfg** передаётся в main, а остальные функции/методы должны использовать свои собственные аргументы т.е. если ты сейчас используешь **cfg.sly_to_int.save_dir**, то его нужно изменить на **save_dir** и передавать его значение

2023-02-16 17:41 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +import pandas as pd
Зачем нам 2 импорта?

2023-02-16 17:46 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +        )
Мы не пишем пустую метадату, а хотя должны. У тебя сохраняется изображение, но в таблице клетки с координатами и маской остаются пустыми. В общем то, что можно писать, нужно писать типа путь до изображения, стади, серия, слайс и т.д.

2023-02-16 17:47 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +    annotation_path = os.path.join(cfg.sly_to_int.save_dir, 'annotation.csv')
Можем финальную метадату сохранять в xlsx и после процессинга всех данных?

2023-02-16 17:51 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +    main()
Коцептуально предлагаю переделать примерно в такой вид:

**main()** поочередно делает 3 основных вещи:
1. Сначала процессит видео, кропает и сохраняет изображения.
2. Затем процессит всю метадату. После выполнения данной функции возвращается лист датафреймов или словарей.
3. И в конце, стакает все датафреймы/словари и сохраняет метадату.

2023-02-16 20:37 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +    img_name = f'{patient_name}_{series:1d}_{frame["index"]:03d}.png'
Нумерация слайсов должна начинаться с 1-го, а не с 0-го

2023-02-16 20:45 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +                'Slice': slice,
Ты slice объект сюда записываешь т.е. **<class 'slice'>**, а не реальный номер слайса

2023-02-17 19:45 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +):
Чем меньше передаваемых параметров в функцию, тем лучше.

Например часть из них можно было взять из _dataset_

2023-02-17 19:49 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +                        ] = mask_[:, :]
Может использовать класс Polygon и Bitmap у которых уже есть метод crop?

`
a = sly.Polygon(
    interior=figure['geometry']['points']['interior'],
    exterior=figure['geometry']['points']['exterior'],
)
b = a.convert(new_geometry=sly.Bitmap)
`

2023-02-17 19:52 UTC, ViacheslavDanilov commented on src/data/convert_sly.py
> +                        annotation = pd.concat([annotation, pd.DataFrame(result_dict, index=[0])])
Вот эта часть практически дублируется с той, которая выше.

Возможно инициализировать словать или датафрейм nan'ами, а затем заполнять их, если есть соответствующее поле. Если нет, то просто остаются НАНы

2023-02-17 19:52 UTC, ViacheslavDanilov requested changes
NACK

2023-02-21 03:10 UTC, Vladislav26Laptev commented
@ViacheslavDanilov, мне кажется пора это заливать.

2023-02-21 11:15 UTC, ViacheslavDanilov approved these changes
LGTM

2023-02-21 11:20 UTC, ViacheslavDanilov approved these changes
LGTM

2023-02-21 11:22 UTC, merged